# This secrets provider class acrts as a bridge between the Secrets Store CSI Driver and AWS Secrets Manager.
# It defines how secrets from AWS Secrets Manager should be accessed and used within Kubernetes pods.
# The provider specifies the secrets to be retrieved, their types, and how they
# should be mapped to environment variables or files within the pods. By using this
# SecretProviderClass, Kubernetes applications can securely access secrets stored in
# AWS Secrets Manager without hardcoding sensitive information in their configurations.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-db-secrets
spec:
  provider: aws # Specifies that the secrets will be retrieved from AWS Secrets Manager.
  parameters:
    # List item defines what secrets to retrieve from AWS Secrets Manager and how to map them to environment variables or files in the pods:
    objects: |
      - objectName: "catalog-db-secret-1" # The name of the secret in AWS Secrets Manager to retrieve.
        objectType: "secretsmanager"
        
        # This picks the specific key-value pairs from the secret and maps them to environment variables in the pods:
        jmesPath: 
          - path: "MYSQL_USER"
            objectAlias: "MYSQL_USER"
          - path: "MYSQL_PASSWORD"
            objectAlias: "MYSQL_PASSWORD"
    
    # Specifies that the secrets should be accessed using the pod's IAM role (if using IRSA):
    usePodIdentity: "true"
